driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-5.11
  - name: centos-6.7
  - name: centos-7.2
  - name: fedora-22

suites:
  - name: default
    run_list:
      - recipe[yum::default]
      - recipe[yum_test::test_repo]
  - name: dnf_compat
    run_list:
      - recipe[yum::dnf_yum_compat]
      - recipe[yum_test::test_dnf_compat]
    includes: fedora-22
