default['file']['wordpress'] = 'https://github.com/yhidetoshi/wordpress'
default['path']['wordpress'] = '/var/www/wordpress'
default['web']['name'] = 'nginx'
default['wordpress']['mysql_pw'] = 'wordpress'
default['mysql']['db_name'] = 'wordpress'
default['mysql']['user']['name']= 'wordpress'
default['mysql']['user']['password'] = 'wordpress'
